#!/bin/bash

curl "https://gwosc.org/archive/data/DiscO4a_16KHZ_R1/1384120320/H-H1_GWOSC_DiscO4a_16KHZ_R1-1384779776-4096.gwf" -o H1-strain.gwf
curl "https://gwosc.org/archive/data/DiscO4a_16KHZ_R1/1384120320/L-L1_GWOSC_DiscO4a_16KHZ_R1-1384779776-4096.gwf" -o L1-strain.gwf
